server.port=${PORT:8080}
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:hospital_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=${DATABASE_DRIVER:org.h2.Driver}
spring.sql.init.mode=${SQL_INIT_MODE:always}
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
server.error.include-message=always
server.error.include-exception=true
server.error.include-binding-errors=always
